name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of Godot Engine"
        required: true
        type: choice
        options:
          - 4.4-stable
          - 4.3-stable
          - 4.2.2-stable
          - 4.2.1-stable
          - 4.2-stable

jobs:
  build:
    name: Build Godot Engine ${{ github.event.inputs.tag }} in ${{ matrix.mode }} mode on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        mode: [debug, release]
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libx11-dev \
            libxcursor-dev \
            libxinerama-dev \
            libgl1-mesa-dev \
            libglu-dev \
            libasound2-dev \
            libpulse-dev 
            \libudev-dev \
            libxi-dev \
            libxrandr-dev \
            yasm

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Godot Engine source code
        run: |
          python download.py --tag ${{ github.event.inputs.tag }}

      - name: Build export templates
        run: |
          python build.py  --mode ${{ matrix.mode }}
