name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of Godot Engine"
        required: true
        type: choice
        options:
          - 4.4-stable
          - 4.3-stable
          - 4.2.2-stable
          - 4.2.1-stable
          - 4.2-stable

jobs:
  release:
    name: Release export templates
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      release_id: ${{ steps.release_step.outputs.id }}

    steps:
      - name: Get timestamp
        id: timestamp
        run: |
          echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: GH Release
        id: release_step
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.tag }}-${{ steps.timestamp.outputs.timestamp }}
          tag_name: ${{ github.event.inputs.tag }}-${{ steps.timestamp.outputs.timestamp }}
          body: |
            Custom export templates for Godot Engine ${{ github.event.inputs.tag }}

  build:
    name: Build Godot Engine ${{ github.event.inputs.tag }} in ${{ matrix.mode }} mode on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    needs: release

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        mode: [debug, release]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libx11-dev \
            libxcursor-dev \
            libxinerama-dev \
            libgl1-mesa-dev \
            libglu-dev \
            libasound2-dev \
            libpulse-dev \
            libudev-dev \
            libxi-dev \
            libxrandr-dev \
            libwayland-dev \
            yasm

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Godot Engine source code
        run: |
          python download.py --tag ${{ github.event.inputs.tag }}

      - name: Build export templates
        run: |
          python build.py --mode ${{ matrix.mode }}

      - name: Use UPX to compress export templates
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            workspace/godot/bin/*

      - name: Zip export templates
        run: |
          cd workspace/godot/bin
          7z a  ../../../${{ github.event.inputs.tag }}-${{ matrix.os }}-${{ matrix.mode }}.zip *

      - name: Upload export templates
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.release.outputs.release_id }}/assets?name=${{ github.event.inputs.tag }}-${{ matrix.os }}-${{ matrix.mode }}.zip" \
          --data-binary @"${{ github.event.inputs.tag }}-${{ matrix.os }}-${{ matrix.mode }}.zip"
