name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of Godot Engine
        required: true
        type: choice
        options:
          - 4.4.1-stable
          - 4.4-stable
          - 4.3-stable
          - 4.2.2-stable
          - 4.2.1-stable
          - 4.2-stable

jobs:
  release:
    name: Release export templates
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      release_tag: ${{ steps.release_tag.outputs.release_tag }}

    steps:
      - name: Get release tag
        id: release_tag
        run: |
          release_tag="${{ github.event.inputs.tag }}-$(date +%s)"
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT

      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.release_tag.outputs.release_tag }}
          tag_name: ${{ steps.release_tag.outputs.release_tag }}
          body: |
            Custom export templates for Godot Engine ${{ github.event.inputs.tag }}

  build-desktop:
    name: Build export templates for ${{ github.event.inputs.tag }} in ${{ matrix.mode }} mode on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    needs: release

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        mode: [debug, release]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libx11-dev \
            libxcursor-dev \
            libxinerama-dev \
            libgl1-mesa-dev \
            libglu-dev \
            libasound2-dev \
            libpulse-dev \
            libudev-dev \
            libxi-dev \
            libxrandr-dev \
            libwayland-dev \
            yasm

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Godot Engine source code
        run: |
          python download-desktop.py --tag ${{ github.event.inputs.tag }}

      - name: Build export templates
        run: |
          python build-desktop.py --mode ${{ matrix.mode }}

      - name: Use UPX to compress export templates
        if: matrix.mode == 'release'
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            workspace/godot/bin/*

      - name: Zip export templates
        run: |
          cd workspace/godot/bin
          7z a  ../../../${{ github.event.inputs.tag }}-${{ matrix.os }}-${{ matrix.mode }}.zip *

      - name: Upload export templates
        run: |
          gh release upload ${{ needs.release.outputs.release_tag }} ${{ github.event.inputs.tag }}-${{ matrix.os }}-${{ matrix.mode }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

  build-android:
    name: Build export templates for ${{ github.event.inputs.tag }} in ${{ matrix.mode }} mode
    runs-on: ubuntu-latest

    needs: release

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        mode: [debug, release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Godot Engine source code
        run: |
          python download-android.py --tag ${{ github.event.inputs.tag }}

      - name: Build export templates
        run: |
          python build-android.py --mode ${{ matrix.mode }}

      - name: Zip export templates
        run: |
          cd workspace/godot/bin
          7z a  ../../../${{ github.event.inputs.tag }}-android-${{ matrix.mode }}.zip android_${{ matrix.mode }}.apk android_source.zip

      - name: Upload export templates
        run: |
          gh release upload ${{ needs.release.outputs.release_tag }} ${{ github.event.inputs.tag }}-android-${{ matrix.mode }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
